import type { FetchFrequency, SourceTrustLevel, SourceType } from "@/lib/content/types";

export interface SeedSourceProfile {
  name: string;
  sourceType: SourceType;
  sourceUrl: string;
  rssUrl: string | null;
  categoryFocus: string[];
  region: string;
  trustLevel: SourceTrustLevel;
  fetchFrequency: FetchFrequency;
  ruleProfile: string;
}

export const seedSourceProfiles: SeedSourceProfile[] = [
  {
    name: "Koninklijke Horeca Nederland",
    sourceType: "rss",
    sourceUrl: "https://www.khn.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:khn.nl&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["horeca_nieuws", "wetgeving", "ondernemen"],
    region: "nl",
    trustLevel: "verified",
    fetchFrequency: "daily",
    ruleProfile: "regulation_priority",
  },
  {
    name: "NU.nl Economie",
    sourceType: "rss",
    sourceUrl: "https://www.nu.nl/economie",
    rssUrl: "https://www.nu.nl/rss/Economie",
    categoryFocus: ["wetgeving", "arbeidsmarkt", "horeca_nieuws"],
    region: "nl",
    trustLevel: "verified",
    fetchFrequency: "daily",
    ruleProfile: "regulation_priority",
  },
  {
    name: "Misset Horeca",
    sourceType: "rss",
    sourceUrl: "https://www.missethoreca.nl",
    rssUrl: "https://www.missethoreca.nl/rss",
    categoryFocus: ["horeca_nieuws", "hospitality_trends", "operations"],
    region: "nl",
    trustLevel: "high",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "Google News - Horeca Nederland",
    sourceType: "rss",
    sourceUrl: "https://news.google.com",
    rssUrl: "https://news.google.com/rss/search?q=horeca+personeel+OR+horeca+cao+OR+horeca+vergunning+OR+hospitality+staffing&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["horeca_nieuws", "arbeidsmarkt", "wetgeving"],
    region: "nl",
    trustLevel: "medium",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "NOS Economie",
    sourceType: "rss",
    sourceUrl: "https://nos.nl/economie",
    rssUrl: "https://feeds.nos.nl/nosnieuwseconomie",
    categoryFocus: ["arbeidsmarkt", "wetgeving", "horeca_nieuws"],
    region: "nl",
    trustLevel: "verified",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "RTL Nieuws",
    sourceType: "rss",
    sourceUrl: "https://www.rtl.nl",
    rssUrl: "https://www.rtlnieuws.nl/rss.xml",
    categoryFocus: ["arbeidsmarkt", "horeca_nieuws", "wetgeving"],
    region: "nl",
    trustLevel: "high",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "Flexmarkt",
    sourceType: "rss",
    sourceUrl: "https://www.flexmarkt.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:flexmarkt.nl&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["recruitment", "arbeidsmarkt", "wetgeving"],
    region: "nl",
    trustLevel: "high",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "PW.nl (Personeelswereld)",
    sourceType: "rss",
    sourceUrl: "https://www.pw.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:pw.nl+arbeidsrecht+OR+HR+OR+personeel&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["hr", "wetgeving", "arbeidsmarkt"],
    region: "nl",
    trustLevel: "high",
    fetchFrequency: "daily",
    ruleProfile: "regulation_priority",
  },
  {
    name: "Rijksoverheid - SZW",
    sourceType: "rss",
    sourceUrl: "https://www.rijksoverheid.nl/ministeries/szw",
    rssUrl: "https://feeds.rijksoverheid.nl/ministeries/szw.rss",
    categoryFocus: ["wetgeving", "arbeidsmarkt", "compliance"],
    region: "nl",
    trustLevel: "verified",
    fetchFrequency: "daily",
    ruleProfile: "regulation_priority",
  },
  {
    name: "FNV Horeca",
    sourceType: "rss",
    sourceUrl: "https://www.fnv.nl/sector-en-cao/alle-sectoren/horeca",
    rssUrl: "https://news.google.com/rss/search?q=FNV+horeca+OR+cao+horeca+OR+FNV+uitzend&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["horeca_nieuws", "wetgeving", "arbeidsmarkt"],
    region: "nl",
    trustLevel: "high",
    fetchFrequency: "daily",
    ruleProfile: "regulation_priority",
  },
  {
    name: "De Ondernemer",
    sourceType: "rss",
    sourceUrl: "https://www.deondernemer.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:deondernemer.nl+personeel+OR+mkb+OR+ondernemen&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["ondernemen", "hr", "arbeidsmarkt"],
    region: "nl",
    trustLevel: "medium",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "ABN AMRO Insights Horeca",
    sourceType: "rss",
    sourceUrl: "https://www.abnamro.nl/nl/zakelijk/insights/sectoren/horeca.html",
    rssUrl: "https://news.google.com/rss/search?q=ABN+AMRO+horeca+OR+hospitality+sector+rapport&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["horeca_nieuws", "hospitality_trends", "economie"],
    region: "nl",
    trustLevel: "high",
    fetchFrequency: "weekly",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "UWV Arbeidsmarktinfo",
    sourceType: "rss",
    sourceUrl: "https://www.uwv.nl/nl/werkgevers",
    rssUrl: "https://news.google.com/rss/search?q=UWV+arbeidsmarkt+OR+werkloosheid+OR+vacatures+cijfers&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["arbeidsmarkt", "economie", "recruitment"],
    region: "nl",
    trustLevel: "verified",
    fetchFrequency: "weekly",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "Hospitality Management",
    sourceType: "rss",
    sourceUrl: "https://www.hospitalitymanagement.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:hospitalitymanagement.nl+OR+%22hospitality+management%22+hotel+nederland&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["hotel_nieuws", "hospitality_trends", "operations"],
    region: "nl",
    trustLevel: "medium",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "RTV Utrecht",
    sourceType: "rss",
    sourceUrl: "https://www.rtvutrecht.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:rtvutrecht.nl+horeca+OR+personeel+OR+ondernemer+OR+werk&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["horeca_nieuws", "arbeidsmarkt", "ondernemen"],
    region: "nl-utrecht",
    trustLevel: "medium",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "AT5 Amsterdam",
    sourceType: "rss",
    sourceUrl: "https://www.at5.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:at5.nl+horeca+OR+personeel+OR+ondernemer+OR+werk&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["horeca_nieuws", "arbeidsmarkt", "ondernemen"],
    region: "nl-amsterdam",
    trustLevel: "medium",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "Rijnmond (Rotterdam)",
    sourceType: "rss",
    sourceUrl: "https://www.rijnmond.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:rijnmond.nl+horeca+OR+personeel+OR+ondernemer+OR+werk&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["horeca_nieuws", "arbeidsmarkt", "ondernemen"],
    region: "nl-rotterdam",
    trustLevel: "medium",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "Studio040 (Eindhoven)",
    sourceType: "rss",
    sourceUrl: "https://www.studio040.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:studio040.nl+horeca+OR+personeel+OR+ondernemer+OR+werk&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["horeca_nieuws", "arbeidsmarkt", "ondernemen"],
    region: "nl-eindhoven",
    trustLevel: "medium",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  // ── Extra bronnen ──
  {
    name: "Het Financieele Dagblad",
    sourceType: "rss",
    sourceUrl: "https://fd.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:fd.nl+horeca+OR+uitzend+OR+arbeidsmarkt+OR+personeel&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["economie", "arbeidsmarkt", "ondernemen"],
    region: "nl",
    trustLevel: "verified",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "Telegraaf Financieel",
    sourceType: "rss",
    sourceUrl: "https://www.telegraaf.nl/financieel",
    rssUrl: "https://www.telegraaf.nl/rss/financieel",
    categoryFocus: ["economie", "arbeidsmarkt", "ondernemen"],
    region: "nl",
    trustLevel: "high",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "CBS Nieuws",
    sourceType: "rss",
    sourceUrl: "https://www.cbs.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:cbs.nl+arbeidsmarkt+OR+werkloosheid+OR+vacatures+OR+horeca&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["arbeidsmarkt", "economie"],
    region: "nl",
    trustLevel: "verified",
    fetchFrequency: "weekly",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "Sprout",
    sourceType: "rss",
    sourceUrl: "https://www.sprout.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:sprout.nl+personeel+OR+ondernemen+OR+mkb+OR+startup&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["ondernemen", "hr", "economie"],
    region: "nl",
    trustLevel: "medium",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "MKB-Nederland",
    sourceType: "rss",
    sourceUrl: "https://www.mkb.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:mkb.nl+personeel+OR+ondernemen+OR+arbeidsmarkt&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["ondernemen", "wetgeving", "arbeidsmarkt"],
    region: "nl",
    trustLevel: "high",
    fetchFrequency: "daily",
    ruleProfile: "regulation_priority",
  },
  {
    name: "Werktrends.nl",
    sourceType: "rss",
    sourceUrl: "https://www.werktrends.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:werktrends.nl+OR+%22werktrends%22+arbeidsmarkt+personeel&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["arbeidsmarkt", "recruitment", "hr"],
    region: "nl",
    trustLevel: "medium",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "NBBU (Uitzendbranche)",
    sourceType: "rss",
    sourceUrl: "https://www.nbbu.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:nbbu.nl+OR+NBBU+uitzend+OR+flexwerk&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["recruitment", "wetgeving", "arbeidsmarkt"],
    region: "nl",
    trustLevel: "verified",
    fetchFrequency: "daily",
    ruleProfile: "regulation_priority",
  },
  {
    name: "ABU (Uitzendbranche)",
    sourceType: "rss",
    sourceUrl: "https://www.abu.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:abu.nl+OR+ABU+uitzend+OR+flexwerk+OR+detachering&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["recruitment", "wetgeving", "arbeidsmarkt"],
    region: "nl",
    trustLevel: "verified",
    fetchFrequency: "daily",
    ruleProfile: "regulation_priority",
  },
  {
    name: "Google News - ZZP & Schijnzelfstandigheid",
    sourceType: "rss",
    sourceUrl: "https://news.google.com",
    rssUrl: "https://news.google.com/rss/search?q=zzp+schijnzelfstandigheid+OR+wet+dba+OR+modelovereenkomst+OR+zelfstandige+handhaving&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["zzp", "wetgeving", "compliance"],
    region: "nl",
    trustLevel: "medium",
    fetchFrequency: "daily",
    ruleProfile: "regulation_priority",
  },
  {
    name: "Google News - Arbeidsmigratie",
    sourceType: "rss",
    sourceUrl: "https://news.google.com",
    rssUrl: "https://news.google.com/rss/search?q=arbeidsmigratie+OR+arbeidsmigranten+OR+kennismigrant+OR+werkvergunning+nederland&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["arbeidsmigratie", "wetgeving", "arbeidsmarkt"],
    region: "nl",
    trustLevel: "medium",
    fetchFrequency: "daily",
    ruleProfile: "regulation_priority",
  },
  {
    name: "Entree Magazine (Horeca)",
    sourceType: "rss",
    sourceUrl: "https://www.entreemagazine.nl",
    rssUrl: "https://news.google.com/rss/search?q=site:entreemagazine.nl+OR+%22entree+magazine%22+horeca&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["horeca_nieuws", "hospitality_trends", "operations"],
    region: "nl",
    trustLevel: "medium",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
  {
    name: "Hotelspecials Nieuws",
    sourceType: "rss",
    sourceUrl: "https://www.hotelspecials.nl",
    rssUrl: "https://news.google.com/rss/search?q=hotel+nederland+personeel+OR+hospitality+OR+hotelbranche+personeelstekort&hl=nl&gl=NL&ceid=NL:nl",
    categoryFocus: ["hotel_nieuws", "hospitality_trends", "arbeidsmarkt"],
    region: "nl",
    trustLevel: "medium",
    fetchFrequency: "daily",
    ruleProfile: "staffing_market_watch",
  },
];
