-- FAQ Items for TopTalent Jobs
-- Generated: 2026-03-12
-- Total: 90 items across 8 categories

INSERT INTO faq_items (id, question, answer, category, subcategory, source, status, slug, priority, view_count, created_at, updated_at)
VALUES
-- CATEGORY: Kosten & Tarieven (12 items)
(
  gen_random_uuid(),
  'Wat zijn de kosten voor het inhuren van horecapersoneel?',
  $$Onze tarieven zijn volledig transparant en afhankelijk van de functie en ervaring van het personeel. Voor bediening rekenen we gemiddeld €18-22 per uur, voor koks €22-28 per uur. Deze tarieven zijn all-in: inclusief loonkosten, verzekeringen en administratie. We hanteren geen verborgen kosten of opstartkosten.$$,
  'Kosten & Tarieven',
  NULL,
  'generated',
  'published',
  'wat-zijn-de-kosten-voor-het-inhuren-van-horecapersoneel',
  1,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Zijn er opstartkosten of inschrijfkosten?',
  $$Nee, wij werken zonder opstartkosten of inschrijfkosten. Je betaalt alleen voor de daadwerkelijk gewerkte uren van het personeel. Ons doel is om de samenwerking zo laagdrempelig mogelijk te maken voor horecaondernemers.$$,
  'Kosten & Tarieven',
  NULL,
  'generated',
  'published',
  'zijn-er-opstartkosten-of-inschrijfkosten',
  2,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat is het minimale aantal uren dat ik moet afnemen?',
  $$Wij hanteren geen minimum aantal uren. Of je nu iemand nodig hebt voor een avonddienst van 4 uur of voor een volledig weekend, wij denken graag met je mee. Flexibiliteit staat bij ons centraal.$$,
  'Kosten & Tarieven',
  NULL,
  'generated',
  'published',
  'wat-is-het-minimale-aantal-uren-dat-ik-moet-afnemen',
  3,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Krijg ik korting bij langdurige samenwerking?',
  $$Bij structurele samenwerking of grotere volumes bieden wij maatwerk tarieven aan. Neem contact met ons op via +31 6 49 71 37 66 om de mogelijkheden te bespreken. We kijken altijd naar een win-win situatie voor beide partijen.$$,
  'Kosten & Tarieven',
  NULL,
  'generated',
  'published',
  'krijg-ik-korting-bij-langdurige-samenwerking',
  4,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wanneer moet ik betalen voor ingehuurd personeel?',
  $$Wij werken met standaard betalingstermijnen van 14 dagen na factuurdatum. Voor nieuwe klanten kan een kortere betalingstermijn of vooruitbetaling van toepassing zijn. De factuur ontvang je wekelijks of per periode, afhankelijk van wat het beste bij jouw administratie past.$$,
  'Kosten & Tarieven',
  NULL,
  'generated',
  'published',
  'wanneer-moet-ik-betalen-voor-ingehuurd-personeel',
  5,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat gebeurt er als een medewerker ziek wordt?',
  $$Bij ziekte van een medewerker betaal je alleen voor de daadwerkelijk gewerkte uren. Wij zorgen waar mogelijk voor vervanging binnen 24 uur, zodat je operatie doorgang kan vinden. Het ziekteverzuim risico ligt bij ons als uitzendbureau.$$,
  'Kosten & Tarieven',
  NULL,
  'generated',
  'published',
  'wat-gebeurt-er-als-een-medewerker-ziek-wordt',
  6,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Zijn de tarieven inclusief of exclusief BTW?',
  $$Alle genoemde tarieven zijn exclusief 21% BTW. Voor BTW-plichtige ondernemingen is dit geen extra kostenpost, aangezien je de BTW kunt terugvorderen. Op de offerte en factuur staat dit altijd duidelijk vermeld.$$,
  'Kosten & Tarieven',
  NULL,
  'generated',
  'published',
  'zijn-de-tarieven-inclusief-of-exclusief-btw',
  7,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat kost het om een spoedinzet te regelen?',
  $$Voor spoedaanvragen binnen 24 uur rekenen wij geen toeslag. Snelheid is een van onze kernwaarden. Alleen bij aanvragen binnen 4 uur kan in sommige gevallen een kleine spoedtoeslag van 10-15% van toepassing zijn, afhankelijk van de beschikbaarheid.$$,
  'Kosten & Tarieven',
  NULL,
  'generated',
  'published',
  'wat-kost-het-om-een-spoedinzet-te-regelen',
  8,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Betaal ik meer voor weekenden en feestdagen?',
  $$Ja, voor werk op zondag en feestdagen hanteren wij de wettelijke toeslagen zoals die ook voor eigen personeel gelden. Zaterdagen vallen onder het normale tarief. We communiceren deze toeslagen altijd vooraf, zodat er geen verrassingen zijn.$$,
  'Kosten & Tarieven',
  NULL,
  'generated',
  'published',
  'betaal-ik-meer-voor-weekenden-en-feestdagen',
  9,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kan ik een offerte aanvragen voordat ik boek?',
  $$Zeker! Via onze website of telefonisch kun je binnen 15 minuten een offerte op maat ontvangen. We bespreken je specifieke wensen, het aantal uren en de benodigde functies. De offerte is vrijblijvend en je zit nergens aan vast.$$,
  'Kosten & Tarieven',
  NULL,
  'generated',
  'published',
  'kan-ik-een-offerte-aanvragen-voordat-ik-boek',
  10,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat zijn de kosten voor het overnemen van personeel?',
  $$Als je een van onze medewerkers na een bepaalde periode in vaste dienst wilt nemen, hanteren wij een overnameregeling. De kosten hiervan zijn afhankelijk van de duur van de uitzendperiode en zijn wettelijk gemaximeerd. Na 6 maanden uitzenden is overname doorgaans kosteloos mogelijk.$$,
  'Kosten & Tarieven',
  NULL,
  'generated',
  'published',
  'wat-zijn-de-kosten-voor-het-overnemen-van-personeel',
  11,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Zijn er extra kosten voor reistijd of reiskosten?',
  $$Reistijd rekenen wij niet apart. Reiskosten zijn inbegrepen in het uurtarief voor medewerkers binnen de standaard regio (max 30 km). Voor locaties verder weg kunnen wij een kleine reiskostenvergoeding in rekening brengen, dit bespreken we altijd vooraf.$$,
  'Kosten & Tarieven',
  NULL,
  'generated',
  'published',
  'zijn-er-extra-kosten-voor-reistijd-of-reiskosten',
  12,
  0,
  now(),
  now()
),

-- CATEGORY: Hoe het werkt (12 items)
(
  gen_random_uuid(),
  'Hoe snel kan TopTalent Jobs personeel leveren?',
  $$Wij kunnen binnen 24 uur geschikt horecapersoneel leveren. In veel gevallen zelfs nog sneller. Na je aanvraag stellen wij binnen 15 minuten een matchscore op en nemen contact op met geschikte kandidaten uit ons netwerk. Spoed is onze specialiteit.$$,
  'Hoe het werkt',
  NULL,
  'generated',
  'published',
  'hoe-snel-kan-toptalent-jobs-personeel-leveren',
  1,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hoe vraag ik personeel aan bij TopTalent Jobs?',
  $$Je kunt personeel aanvragen via onze website, telefonisch op +31 6 49 71 37 66, of via e-mail naar info@toptalentjobs.nl. Vertel ons welke functie je zoekt, voor welke datum en tijd, en eventuele specifieke wensen. Wij nemen dan direct contact op met een voorstel.$$,
  'Hoe het werkt',
  NULL,
  'generated',
  'published',
  'hoe-vraag-ik-personeel-aan-bij-toptalent-jobs',
  2,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat is de matchscore en hoe werkt die?',
  $$Onze matchscore is een systeem waarmee we binnen 15 minuten de beste kandidaat voor jouw vacature vinden. We kijken naar ervaring, beschikbaarheid, afstand, eerdere beoordelingen en specifieke vaardigheden. Zo matchen we niet alleen op beschikbaarheid, maar ook op kwaliteit en fit.$$,
  'Hoe het werkt',
  NULL,
  'generated',
  'published',
  'wat-is-de-matchscore-en-hoe-werkt-die',
  3,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kan ik dezelfde medewerker vaker inzetten?',
  $$Absoluut! Als je tevreden bent over een medewerker kun je specifiek om deze persoon vragen voor toekomstige diensten. Wij stimuleren continuïteit omdat dit zorgt voor betere service en minder inwerktijd. Onze vaste medewerkers leren zo jouw bedrijf goed kennen.$$,
  'Hoe het werkt',
  NULL,
  'generated',
  'published',
  'kan-ik-dezelfde-medewerker-vaker-inzetten',
  4,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat gebeurt er na mijn aanvraag?',
  $$Na je aanvraag ontvang je binnen 15 minuten een bevestiging met een of meerdere kandidaten inclusief hun profiel en ervaring. Je krijgt de gelegenheid om het profiel te bekijken en goed of afkeuren. Zodra je akkoord geeft, bevestigen wij de boeking en informeren we de medewerker over alle details.$$,
  'Hoe het werkt',
  NULL,
  'generated',
  'published',
  'wat-gebeurt-er-na-mijn-aanvraag',
  5,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Moet ik een account aanmaken om personeel te boeken?',
  $$Voor je eerste boeking is een account niet verplicht. Voor terugkerende klanten bieden wij een online portal waar je eenvoudig personeel kunt boeken, eerdere diensten kunt inzien en facturen kunt downloaden. Dit maakt het proces nog sneller en gemakkelijker.$$,
  'Hoe het werkt',
  NULL,
  'generated',
  'published',
  'moet-ik-een-account-aanmaken-om-personeel-te-boeken',
  6,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hoe werkt de begeleiding tijdens de dienst?',
  $$De medewerker wordt volledig gebriefd over zijn of haar taken voordat de dienst begint. Tijdens de dienst is de medewerker aanspreekbaar via jouw vaste contactpersoon in de zaak. Mocht er iets zijn, dan zijn wij 24/7 bereikbaar voor support of escalaties.$$,
  'Hoe het werkt',
  NULL,
  'generated',
  'published',
  'hoe-werkt-de-begeleiding-tijdens-de-dienst',
  7,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kan ik een aanvraag annuleren of wijzigen?',
  $$Ja, tot 24 uur voor aanvang van de dienst kun je kosteloos annuleren of wijzigen. Bij annuleringen binnen 24 uur brengen wij 50% van de geplande uren in rekening. Bij no-show rekenen wij het volledige bedrag. Dit om onze medewerkers te beschermen die zich al beschikbaar hebben gehouden.$$,
  'Hoe het werkt',
  NULL,
  'generated',
  'published',
  'kan-ik-een-aanvraag-annuleren-of-wijzigen',
  8,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Werken jullie ook op korte termijn voor grote evenementen?',
  $$Ja, wij zijn gespecialiseerd in last-minute oplossingen. Voor grote evenementen adviseren wij wel om minimaal 5-7 dagen van tevoren contact op te nemen, zodat we voldoende personeel kunnen mobiliseren. Maar ook voor spoedgevallen doen we ons uiterste best.$$,
  'Hoe het werkt',
  NULL,
  'generated',
  'published',
  'werken-jullie-ook-op-korte-termijn-voor-grote-evenementen',
  9,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hoe zit het met de inwerktijd van nieuw personeel?',
  $$Wij sturen alleen ervaren medewerkers die snel kunnen schakelen. Voor specifieke systemen of menu''s is een korte briefing meestal voldoende. Als je de eerste keer met een nieuwe medewerker werkt, adviseren wij 15-30 minuten inwerkttijd in te plannen voor een optimale start.$$,
  'Hoe het werkt',
  NULL,
  'generated',
  'published',
  'hoe-zit-het-met-de-inwerktijd-van-nieuw-personeel',
  10,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Krijg ik een vaste contactpersoon bij TopTalent Jobs?',
  $$Ja, bij structurele samenwerking krijg je een vaste accountmanager die jouw bedrijf en wensen kent. Voor incidentele opdrachten werk je met ons algemene team, maar ook zij hebben direct toegang tot alle relevante informatie over jouw zaak en voorkeuren.$$,
  'Hoe het werkt',
  NULL,
  'generated',
  'published',
  'krijg-ik-een-vaste-contactpersoon-bij-toptalent-jobs',
  11,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hoe werkt de urenregistratie?',
  $$De medewerker registreert de gewerkte uren digitaal via onze app. Jij krijgt aan het einde van de dienst een bevestiging ter goedkeuring. Dit voorkomt discussies achteraf en zorgt voor transparantie. De goedgekeurde uren worden vervolgens gebruikt voor de facturering.$$,
  'Hoe het werkt',
  NULL,
  'generated',
  'published',
  'hoe-werkt-de-urenregistratie',
  12,
  0,
  now(),
  now()
),

-- CATEGORY: Functies & Personeel (12 items)
(
  gen_random_uuid(),
  'Welke functies kunnen jullie leveren?',
  $$Wij leveren alle gangbare horecafuncties: koks, sous-chefs, bediening, bartenders, afwassers, barista''s, gastheren/gastvrouwen en evenementenpersoneel. Of je nu één kok nodig hebt of een volledig team voor een evenement, wij hebben ervaren mensen beschikbaar.$$,
  'Functies & Personeel',
  NULL,
  'generated',
  'published',
  'welke-functies-kunnen-jullie-leveren',
  1,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hebben jullie ook specialisten zoals sushi-koks of patissiers?',
  $$Ja, wij hebben een netwerk van gespecialiseerd personeel waaronder sushi-koks, patissiers, sommeliers en cocktail-specialisten. Voor dit type functies vragen wij je om enkele dagen voorbereidingstijd, zodat we de juiste specialist kunnen vinden die past bij jouw concept.$$,
  'Functies & Personeel',
  NULL,
  'generated',
  'published',
  'hebben-jullie-ook-specialisten-zoals-sushi-koks-of-patissiers',
  2,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat is het ervaringsniveau van jullie personeel?',
  $$Alle medewerkers in ons netwerk hebben minimaal 1 jaar ervaring in de horeca. Voor leidinggevende posities zoals (sous-)chef of manager eisen wij minimaal 3 jaar relevante ervaring. We screenen iedereen zorgvuldig op ervaring, houding en betrouwbaarheid.$$,
  'Functies & Personeel',
  NULL,
  'generated',
  'published',
  'wat-is-het-ervaringsniveau-van-jullie-personeel',
  3,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kunnen jullie personeel leveren dat specifieke talen spreekt?',
  $$Ja, we hebben meertalig personeel in ons netwerk. Naast Nederlands en Engels hebben we medewerkers die Duits, Frans, Spaans en andere talen spreken. Geef bij je aanvraag aan welke taal gewenst is, dan houden we daar rekening mee in de matching.$$,
  'Functies & Personeel',
  NULL,
  'generated',
  'published',
  'kunnen-jullie-personeel-leveren-dat-specifieke-talen-spreekt',
  4,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Leveren jullie ook managementfuncties zoals bedrijfsleiders?',
  $$Ja, wij kunnen tijdelijke managers, bedrijfsleiders en afdelingshoofden leveren. Dit is interessant bij ziekte, vakantie of tijdens een transitieperiode. Voor managementfuncties werken wij bij voorkeur met een kennismakingsgesprek vooraf.$$,
  'Functies & Personeel',
  NULL,
  'generated',
  'published',
  'leveren-jullie-ook-managementfuncties-zoals-bedrijfsleiders',
  5,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Heeft het personeel alle benodigde certificaten zoals HACCP?',
  $$Ja, alle medewerkers die in de keuken werken hebben een geldig HACCP-certificaat. Voor functies waar specifieke certificaten vereist zijn zoals BHV of een drankvergunning, zorgen wij dat deze op orde zijn. Je kunt hiervan uitgaan bij elke medewerker die we sturen.$$,
  'Functies & Personeel',
  NULL,
  'generated',
  'published',
  'heeft-het-personeel-alle-benodigde-certificaten-zoals-haccp',
  6,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kan ik vooraf kennis maken met het personeel?',
  $$Voor structurele samenwerkingen of leidinggevende functies is een kennismaking mogelijk en zelfs aan te raden. Voor kortdurende opdrachten werken we meestal zonder voorafgaand gesprek, maar ontvang je wel een uitgebreid profiel met foto, ervaring en eerdere beoordelingen.$$,
  'Functies & Personeel',
  NULL,
  'generated',
  'published',
  'kan-ik-vooraf-kennis-maken-met-het-personeel',
  7,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat als ik niet tevreden ben over een medewerker?',
  $$Je tevredenheid staat voorop. Als je niet tevreden bent, neem dan direct contact op tijdens of na de dienst. We zoeken samen naar een oplossing, of dat nu extra begeleiding is of vervanging door een andere medewerker. Feedback helpt ons om de kwaliteit hoog te houden.$$,
  'Functies & Personeel',
  NULL,
  'generated',
  'published',
  'wat-als-ik-niet-tevreden-ben-over-een-medewerker',
  8,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kunnen jullie een volledig team leveren voor een opening?',
  $$Absoluut! Wij hebben ervaring met het bemensen van complete openingsteams, van chef tot afwas. We zorgen ervoor dat het team vooraf elkaar kent en afgestemd is qua ervaring en werkstijl. Dit garandeert een vlotte start van je nieuwe zaak.$$,
  'Functies & Personeel',
  NULL,
  'generated',
  'published',
  'kunnen-jullie-een-volledig-team-leveren-voor-een-opening',
  9,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Leveren jullie ook studenten of alleen ervaren krachten?',
  $$Ons netwerk bestaat voornamelijk uit ervaren professionals, maar we hebben ook gemotiveerde studenten met horeca-ervaring. Voor eenvoudige functies zoals afwas of runner kunnen studenten een goede keuze zijn. Voor meer verantwoordelijke posities zetten we ervaren krachten in.$$,
  'Functies & Personeel',
  NULL,
  'generated',
  'published',
  'leveren-jullie-ook-studenten-of-alleen-ervaren-krachten',
  10,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hoe selecteren jullie de medewerkers voor mijn bedrijf?',
  $$We kijken naar meerdere factoren: de functie-eisen, jouw type bedrijf (fine dining vs. casual), de benodigde ervaring, beschikbaarheid en eerdere prestaties. Onze algoritme geeft binnen 15 minuten een matchscore. Daarnaast kijken onze recruiters handmatig mee voor de beste fit.$$,
  'Functies & Personeel',
  NULL,
  'generated',
  'published',
  'hoe-selecteren-jullie-de-medewerkers-voor-mijn-bedrijf',
  11,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kunnen jullie personeel leveren voor zowel fastfood als fine dining?',
  $$Ja, ons netwerk is breed en geschikt voor alle segmenten. Van fastfood en casual dining tot fine dining en sterrenrestaurants. We hebben ervaring met verschillende concepten en sturen personeel dat past bij het niveau en de sfeer van jouw zaak.$$,
  'Functies & Personeel',
  NULL,
  'generated',
  'published',
  'kunnen-jullie-personeel-leveren-voor-zowel-fastfood-als-fine-dining',
  12,
  0,
  now(),
  now()
),

-- CATEGORY: Contracten & Juridisch (10 items)
(
  gen_random_uuid(),
  'Wat voor soort contract krijg ik met TopTalent Jobs?',
  $$Je krijgt een duidelijke uitzendovereenkomst waarin de voorwaarden, tarieven en afspraken zijn vastgelegd. Voor losse opdrachten werken we vaak met een raamcontract, waarna je per keer een aanvraag doet. Voor structurele samenwerking maken we een uitgebreidere overeenkomst op maat.$$,
  'Contracten & Juridisch',
  NULL,
  'generated',
  'published',
  'wat-voor-soort-contract-krijg-ik-met-toptalent-jobs',
  1,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wie is de werkgever van het ingeleende personeel?',
  $$TopTalent Jobs is de formele werkgever van het ingeleende personeel. Wij dragen de verantwoordelijkheid voor loonbetaling, verzekeringen, arbeidsvoorwaarden en administratie. Jij bent opdrachtgever en geeft leiding aan het werk, maar de juridische werkgeververantwoordelijkheid ligt bij ons.$$,
  'Contracten & Juridisch',
  NULL,
  'generated',
  'published',
  'wie-is-de-werkgever-van-het-ingeleende-personeel',
  2,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Welke verzekeringen zijn er geregeld?',
  $$Alle medewerkers zijn verzekerd via onze bedrijfs-WA-verzekering en arbeidsongeschiktheidsverzekering. Ook de wettelijke verplichtingen zoals WW, WIA en pensioenpremie zijn geregeld. Jij hoeft je hier als opdrachtgever geen zorgen over te maken.$$,
  'Contracten & Juridisch',
  NULL,
  'generated',
  'published',
  'welke-verzekeringen-zijn-er-geregeld',
  3,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat is mijn aansprakelijkheid als opdrachtgever?',
  $$Als opdrachtgever ben je verantwoordelijk voor een veilige werkomgeving en duidelijke werkinstructies. Schade door grove nalatigheid of bewust wangedrag van de medewerker valt onder onze verantwoordelijkheid. Normale bedrijfsschade bij reguliere werkzaamheden is doorgaans gedekt via verzekeringen.$$,
  'Contracten & Juridisch',
  NULL,
  'generated',
  'published',
  'wat-is-mijn-aansprakelijkheid-als-opdrachtgever',
  4,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kan ik het contract tussentijds opzeggen?',
  $$Voor losse opdrachten is er geen sprake van opzegging, die worden per keer geboekt. Bij structurele overeenkomsten hanteren we een opzegtermijn van 1 maand. We proberen altijd eerst in overleg tot een oplossing te komen voordat we tot opzegging overgaan.$$,
  'Contracten & Juridisch',
  NULL,
  'generated',
  'published',
  'kan-ik-het-contract-tussentijds-opzeggen',
  5,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Vallen jullie onder de horeca-CAO?',
  $$Ja, wij werken volgens de cao voor Uitzendkrachten, met daarbinnen de specifieke afspraken voor de horecasector. Dit betekent correcte loonschalen, toeslagen en arbeidsvoorwaarden. Onze medewerkers worden altijd volgens de geldende cao beloond.$$,
  'Contracten & Juridisch',
  NULL,
  'generated',
  'published',
  'vallen-jullie-onder-de-horeca-cao',
  6,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat gebeurt er bij een arbeidsconflict met een medewerker?',
  $$Omdat wij de formele werkgever zijn, handelen wij eventuele arbeidsconflicten af. Mocht er een probleem zijn tussen jou en een medewerker, neem dan direct contact met ons op. Wij treden op als bemiddelaar en zoeken naar een passende oplossing voor beide partijen.$$,
  'Contracten & Juridisch',
  NULL,
  'generated',
  'published',
  'wat-gebeurt-er-bij-een-arbeidsconflict-met-een-medewerker',
  7,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hoe zit het met de AVG en privacy van gegevens?',
  $$Wij nemen privacy zeer serieus en werken volledig AVG-compliant. Persoonsgegevens van medewerkers en klanten worden veilig opgeslagen en alleen gebruikt voor de uitvoering van onze diensten. We delen nooit gegevens met derden zonder toestemming.$$,
  'Contracten & Juridisch',
  NULL,
  'generated',
  'published',
  'hoe-zit-het-met-de-avg-en-privacy-van-gegevens',
  8,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat zijn de algemene voorwaarden van TopTalent Jobs?',
  $$Onze algemene voorwaarden zijn terug te vinden op www.toptalentjobs.nl en worden meegezonden bij het contract. Ze beschrijven onder andere de betalingsvoorwaarden, annuleringsbeleid, aansprakelijkheden en klachtenprocedures. We adviseren deze goed door te nemen.$$,
  'Contracten & Juridisch',
  NULL,
  'generated',
  'published',
  'wat-zijn-de-algemene-voorwaarden-van-toptalent-jobs',
  9,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hoe zit het met geheimhouding en concurrentiebeding?',
  $$Wij hanteren standaard een geheimhoudingsclausule voor onze medewerkers. Indien gewenst kunnen we een specifieke geheimhoudingsovereenkomst opstellen voor jouw bedrijf, bijvoorbeeld bij bijzondere concepten of receptuur. Een concurrentiebeding is bespreekbaar bij langdurige detacheringen.$$,
  'Contracten & Juridisch',
  NULL,
  'generated',
  'published',
  'hoe-zit-het-met-geheimhouding-en-concurrentiebeding',
  10,
  0,
  now(),
  now()
),

-- CATEGORY: Locaties & Beschikbaarheid (10 items)
(
  gen_random_uuid(),
  'In welke steden is TopTalent Jobs actief?',
  $$TopTalent Jobs is actief in Utrecht, Amsterdam, Rotterdam, Den Haag en Eindhoven en omliggende gemeenten. We bedienen de gehele Randstad en zuidoost Nederland. Voor locaties buiten deze regio kunnen we in overleg kijken naar de mogelijkheden.$$,
  'Locaties & Beschikbaarheid',
  NULL,
  'generated',
  'published',
  'in-welke-steden-is-toptalent-jobs-actief',
  1,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Leveren jullie ook personeel buiten de grote steden?',
  $$Ja, we leveren ook in kleinere plaatsen binnen onze werkgebieden. Denk aan plaatsen in de buurt van Utrecht zoals Amersfoort, Zeist en Nieuwegein. Voor locaties verder weg berekenen we eventueel een kleine reiskostenvergoeding, afhankelijk van de afstand.$$,
  'Locaties & Beschikbaarheid',
  NULL,
  'generated',
  'published',
  'leveren-jullie-ook-personeel-buiten-de-grote-steden',
  2,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kunnen jullie personeel leveren voor evenementen door heel Nederland?',
  $$Voor grote evenementen of langdurige opdrachten zijn we bereid om landelijk te opereren. Neem voor deze aanvragen minimaal 2 weken van tevoren contact op, zodat we de logistiek goed kunnen organiseren en mogelijk lokale partners kunnen inschakelen.$$,
  'Locaties & Beschikbaarheid',
  NULL,
  'generated',
  'published',
  'kunnen-jullie-personeel-leveren-voor-evenementen-door-heel-nederland',
  3,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Zijn jullie 24/7 bereikbaar?',
  $$Ja, TopTalent Jobs is 24/7 bereikbaar via ons noodnummer. Voor acute problemen, no-shows of spoedvragen kun je ons altijd bellen op +31 6 49 71 37 66. Voor reguliere aanvragen tijdens kantooruren (ma-vr 09:00-18:00) zijn we telefonisch en per e-mail beschikbaar.$$,
  'Locaties & Beschikbaarheid',
  NULL,
  'generated',
  'published',
  'zijn-jullie-24-7-bereikbaar',
  4,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Werken jullie ook op feestdagen?',
  $$Ja, wij leveren ook personeel op feestdagen zoals Kerst, Oud & Nieuw, Pasen en Koningsdag. Dit zijn vaak drukke dagen in de horeca en wij zorgen ervoor dat ons netwerk beschikbaar is. Wel zijn de wettelijke toeslagen van toepassing.$$,
  'Locaties & Beschikbaarheid',
  NULL,
  'generated',
  'published',
  'werken-jullie-ook-op-feestdagen',
  5,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hoe ver van tevoren moet ik personeel aanvragen?',
  $$Voor de beste beschikbaarheid adviseren we 3-5 dagen van tevoren. Maar dankzij ons grote netwerk kunnen wij meestal ook binnen 24 uur leveren. Voor grote evenementen of teams van 5+ personen is 1-2 weken vooruit boeken verstandig.$$,
  'Locaties & Beschikbaarheid',
  NULL,
  'generated',
  'published',
  'hoe-ver-van-tevoren-moet-ik-personeel-aanvragen',
  6,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat is jullie dekkingsgebied rondom Utrecht?',
  $$Rondom Utrecht bedienen we een straal van ongeveer 30 kilometer. Dit omvat plaatsen als Amersfoort, Veenendaal, Woerden, IJsselstein en Bunnik. Voor grotere afstanden overleggen we per situatie of dit haalbaar is.$$,
  'Locaties & Beschikbaarheid',
  NULL,
  'generated',
  'published',
  'wat-is-jullie-dekkingsgebied-rondom-utrecht',
  7,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Leveren jullie ook op zondag?',
  $$Ja, we leveren ook op zondag. Veel horecabedrijven zijn juist op zondag extra druk en wij zorgen dat er voldoende personeel beschikbaar is. Op zondag zijn wel de cao-toeslagen van toepassing, die doorberekend worden in het uurtarief.$$,
  'Locaties & Beschikbaarheid',
  NULL,
  'generated',
  'published',
  'leveren-jullie-ook-op-zondag',
  8,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kunnen jullie structureel personeel leveren voor vaste dagen?',
  $$Absoluut! We hebben veel klanten waarbij we wekelijks op vaste dagen personeel leveren. Dit geeft jou zekerheid en zorgt voor continuïteit omdat dezelfde medewerkers terugkomen. Voor structurele afspraken maken we aantrekkelijke afspraken.$$,
  'Locaties & Beschikbaarheid',
  NULL,
  'generated',
  'published',
  'kunnen-jullie-structureel-personeel-leveren-voor-vaste-dagen',
  9,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Is er in het hoogseizoen voldoende personeel beschikbaar?',
  $$Het hoogseizoen is inderdaad drukker, maar dankzij ons grote netwerk en proactieve planning kunnen we meestal ook dan leveren. We adviseren wel om in drukke periodes zoals zomer, Kerst en Pasen eerder te boeken, zodat we de beste medewerkers voor je kunnen reserveren.$$,
  'Locaties & Beschikbaarheid',
  NULL,
  'generated',
  'published',
  'is-er-in-het-hoogseizoen-voldoende-personeel-beschikbaar',
  10,
  0,
  now(),
  now()
),

-- CATEGORY: Voor horecamedewerkers (12 items)
(
  gen_random_uuid(),
  'Hoe kan ik mij aanmelden als horecamedewerker bij TopTalent Jobs?',
  $$Je kunt je aanmelden via onze website www.toptalentjobs.nl. Vul je gegevens in, upload je CV en vertel ons over je ervaring. We nemen binnen 2 werkdagen contact op voor een kennismaking. Na goedkeuring word je toegevoegd aan ons netwerk en kun je direct aan de slag.$$,
  'Voor horecamedewerkers',
  NULL,
  'generated',
  'published',
  'hoe-kan-ik-mij-aanmelden-als-horecamedewerker-bij-toptalent-jobs',
  1,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Welke eisen stellen jullie aan nieuwe medewerkers?',
  $$We zoeken mensen met minimaal 1 jaar horeca-ervaring, een flexibele houding en goede sociale vaardigheden. Voor keukenfuncties is een HACCP-certificaat verplicht. Betrouwbaarheid en professionaliteit staan bij ons hoog in het vaandel. Ook vragen we om een VOG (Verklaring Omtrent Gedrag).$$,
  'Voor horecamedewerkers',
  NULL,
  'generated',
  'published',
  'welke-eisen-stellen-jullie-aan-nieuwe-medewerkers',
  2,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hoe word ik betaald als uitzendkracht?',
  $$Je wordt wekelijks of per 4 weken betaald, afhankelijk van jouw voorkeur. Het salaris wordt overgemaakt op je bankrekening. We werken volgens de cao voor uitzendkrachten, inclusief vakantiegeld, toeslagen en alle wettelijke verplichtingen.$$,
  'Voor horecamedewerkers',
  NULL,
  'generated',
  'published',
  'hoe-word-ik-betaald-als-uitzendkracht',
  3,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kan ik zelf aangeven wanneer ik beschikbaar ben?',
  $$Ja, via onze app geef je aan wanneer je beschikbaar bent. Je ontvangt alleen dienstaanbiedingen die passen bij jouw agenda. Je bent volledig vrij om opdrachten te accepteren of af te slaan. Hoe meer je beschikbaar bent, hoe meer diensten we je kunnen aanbieden.$$,
  'Voor horecamedewerkers',
  NULL,
  'generated',
  'published',
  'kan-ik-zelf-aangeven-wanneer-ik-beschikbaar-ben',
  4,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hoeveel kan ik verdienen als uitzendkracht?',
  $$Het loon is afhankelijk van je functie en ervaring. Voor bediening ligt het tussen €13-16 per uur, voor koks tussen €15-20 per uur. Daarbovenop komen toeslagen voor avond, weekend en feestdagen. Met een fulltime beschikbaarheid kun je goed verdienen in de horeca.$$,
  'Voor horecamedewerkers',
  NULL,
  'generated',
  'published',
  'hoeveel-kan-ik-verdienen-als-uitzendkracht',
  5,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Krijg ik een contract of werk ik op oproepbasis?',
  $$Je krijgt een nul-urencontract of een contract voor bepaalde tijd, afhankelijk van je voorkeur en de beschikbaarheid van werk. Bij een nul-urencontract bepaal je zelf wanneer je werkt. Bij structurele diensten kunnen we een contract met vaste uren aanbieden.$$,
  'Voor horecamedewerkers',
  NULL,
  'generated',
  'published',
  'krijg-ik-een-contract-of-werk-ik-op-oproepbasis',
  6,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat gebeurt er als ik een keer niet kan op het laatste moment?',
  $$We begrijpen dat er soms onverwachte situaties ontstaan. Meld je zo snel mogelijk af, bij voorkeur minimaal 4 uur voor aanvang van de dienst. Bij herhaaldelijk te laat afmelden kan dit gevolgen hebben voor toekomstige dienstaanbiedingen. Betrouwbaarheid is belangrijk.$$,
  'Voor horecamedewerkers',
  NULL,
  'generated',
  'published',
  'wat-gebeurt-er-als-ik-een-keer-niet-kan-op-het-laatste-moment',
  7,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Krijg ik reiskosten vergoed?',
  $$Ja, voor diensten verder dan 10 kilometer van je woonadres vergoed we reiskosten volgens de cao. Dit is €0,21 per kilometer. Je declareert dit eenvoudig via onze app en de vergoeding wordt meegenomen in je salaris.$$,
  'Voor horecamedewerkers',
  NULL,
  'generated',
  'published',
  'krijg-ik-reiskosten-vergoed',
  8,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kan ik doorgroeien naar een vast contract bij TopTalent Jobs?',
  $$Bij goede prestaties en voldoende beschikbaar werk kunnen we je een vast contract aanbieden. Daarnaast krijg je regelmatig de kans om door te stromen naar een vaste baan bij een van onze opdrachtgevers. Wij ondersteunen je graag in je carrière.$$,
  'Voor horecamedewerkers',
  NULL,
  'generated',
  'published',
  'kan-ik-doorgroeien-naar-een-vast-contract-bij-toptalent-jobs',
  9,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Moet ik zelf mijn werkkleding regelen?',
  $$Voor veel functies wordt werkkleding verstrekt door de opdrachtgever ter plekke. Voor sommige functies zoals bediening vragen we dat je zelf beschikt over een basis zwart-wit outfit. Specifieke kledingwensen communiceren we altijd vooraf bij de dienstaanbieding.$$,
  'Voor horecamedewerkers',
  NULL,
  'generated',
  'published',
  'moet-ik-zelf-mijn-werkkleding-regelen',
  10,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Bieden jullie ook trainingen of opleidingen aan?',
  $$Ja, we organiseren regelmatig trainingen en workshops voor onze medewerkers. Denk aan HACCP-cursussen, barista-training of hospitality-workshops. Deze zijn vaak gratis of tegen gereduceerd tarief. Zo investeren we in jouw ontwikkeling en blijf je up-to-date.$$,
  'Voor horecamedewerkers',
  NULL,
  'generated',
  'published',
  'bieden-jullie-ook-trainingen-of-opleidingen-aan',
  11,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hoe werkt de app van TopTalent Jobs?',
  $$Via de app zie je beschikbare diensten, kun je je beschikbaarheid aangeven, uren registreren en communiceren met ons kantoor. Je ontvangt pushnotificaties bij nieuwe dienstaanbiedingen en kunt direct accepteren. De app maakt flexwerken super eenvoudig en overzichtelijk.$$,
  'Voor horecamedewerkers',
  NULL,
  'generated',
  'published',
  'hoe-werkt-de-app-van-toptalent-jobs',
  12,
  0,
  now(),
  now()
),

-- CATEGORY: Evenementen & Catering (10 items)
(
  gen_random_uuid(),
  'Leveren jullie personeel voor bruiloften en partijen?',
  $$Ja, wij hebben ruime ervaring met bruiloften, verjaardagen en bedrijfsfeesten. We kunnen zowel keukenpersoneel als bediening en barmedewerkers leveren. Vertel ons het type evenement, aantal gasten en gewenste diensten, dan stellen we een passend team samen.$$,
  'Evenementen & Catering',
  NULL,
  'generated',
  'published',
  'leveren-jullie-personeel-voor-bruiloften-en-partijen',
  1,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kunnen jullie een compleet cateringteam leveren?',
  $$Absoluut! We kunnen een volledig cateringteam samenstellen van chef tot serveermedewerkers. Voor grotere evenementen leveren we ook een teamleider die ter plekke de regie voert. Zo weet je zeker dat alles soepel verloopt.$$,
  'Evenementen & Catering',
  NULL,
  'generated',
  'published',
  'kunnen-jullie-een-compleet-cateringteam-leveren',
  2,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat is het minimale aantal personen voor een evenement?',
  $$Er is geen minimum. We leveren ook personeel voor kleinere evenementen vanaf 20-30 gasten. Of je nu een intiem diner organiseert of een groot festival, wij schalen mee met je wensen. Voor hele kleine evenementen kan een minimale boekingstijd van 4 uur gelden.$$,
  'Evenementen & Catering',
  NULL,
  'generated',
  'published',
  'wat-is-het-minimale-aantal-personen-voor-een-evenement',
  3,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Leveren jullie ook personeel voor festivals en beurzen?',
  $$Ja, we hebben veel ervaring met grotere evenementen zoals festivals, beurzen en conferenties. We kunnen grote aantallen medewerkers mobiliseren voor drankstands, foodtrucks en hospitality areas. Neem hiervoor wel minimaal 2-3 weken van tevoren contact op.$$,
  'Evenementen & Catering',
  NULL,
  'generated',
  'published',
  'leveren-jullie-ook-personeel-voor-festivals-en-beurzen',
  4,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kunnen jullie personeel leveren voor buitenlocaties?',
  $$Ja, we leveren ook personeel voor buitenlocaties zoals tuinen, parken, stranden en landgoederen. Zolang de locatie binnen ons werkgebied ligt, is dit geen probleem. Geef bij de aanvraag wel de specifieke locatie door zodat we dit kunnen meenemen in de planning.$$,
  'Evenementen & Catering',
  NULL,
  'generated',
  'published',
  'kunnen-jullie-personeel-leveren-voor-buitenlocaties',
  5,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat gebeurt er als het evenement langer duurt dan gepland?',
  $$Overwerk is geen probleem, zolang de medewerker beschikbaar is. We rekenen de extra uren tegen hetzelfde uurtarief. Probeer wel van tevoren in te schatten of het evenement mogelijk langer duurt, dan kunnen we daar rekening mee houden in de planning.$$,
  'Evenementen & Catering',
  NULL,
  'generated',
  'published',
  'wat-gebeurt-er-als-het-evenement-langer-duurt-dan-gepland',
  6,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Leveren jullie ook personeel voor meerdaagse evenementen?',
  $$Ja, voor meerdaagse evenementen zoals festivals, congressen of beurzen kunnen we personeel leveren voor de volledige duur. Dit heeft als voordeel dat hetzelfde team gedurende het hele evenement aanwezig is, wat zorgt voor continuïteit en efficiëntie.$$,
  'Evenementen & Catering',
  NULL,
  'generated',
  'published',
  'leveren-jullie-ook-personeel-voor-meerdaagse-evenementen',
  7,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kunnen jullie helpen met de planning van personeel voor een evenement?',
  $$Ja, we denken graag mee over hoeveel personeel je nodig hebt op basis van het aantal gasten, type evenement en gewenste service. Met onze ervaring kunnen we je adviseren over de juiste bezetting zodat je niet te veel of te weinig personeel inzet.$$,
  'Evenementen & Catering',
  NULL,
  'generated',
  'published',
  'kunnen-jullie-helpen-met-de-planning-van-personeel-voor-evenement',
  8,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Leveren jullie ook baristas voor koffiecorners bij evenementen?',
  $$Ja, we hebben ervaren baristas in ons netwerk die je koffiecorner kunnen bemannen. Ze beschikken over eigen ervaring met professionele espressomachines en kunnen verschillende koffiespecialiteiten maken. Perfect voor congressen, beurzen en bedrijfsevenementen.$$,
  'Evenementen & Catering',
  NULL,
  'generated',
  'published',
  'leveren-jullie-ook-baristas-voor-koffiecorners-bij-evenementen',
  9,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat als het weer tegenzit bij een buiten evenement?',
  $$Weersomstandigheden zijn buiten onze controle, maar wij leveren altijd het afgesproken personeel. Of het evenement doorgaat is aan jou als organisator. Bij annulering door slecht weer gelden dezelfde voorwaarden als reguliere annuleringen: tot 24 uur van tevoren kosteloos.$$,
  'Evenementen & Catering',
  NULL,
  'generated',
  'published',
  'wat-als-het-weer-tegenzit-bij-een-buiten-evenement',
  10,
  0,
  now(),
  now()
),

-- CATEGORY: Kwaliteit & Screening (12 items)
(
  gen_random_uuid(),
  'Hoe controleren jullie de kwaliteit van medewerkers?',
  $$We screenen alle medewerkers vooraf op ervaring, certificaten en betrouwbaarheid. Na elke dienst ontvangen we feedback van de opdrachtgever, die we gebruiken voor onze beoordeling. Medewerkers met structureel lage beoordelingen worden uit ons netwerk verwijderd.$$,
  'Kwaliteit & Screening',
  NULL,
  'generated',
  'published',
  'hoe-controleren-jullie-de-kwaliteit-van-medewerkers',
  1,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Doen jullie een referentiecheck bij nieuwe medewerkers?',
  $$Ja, bij elke nieuwe aanmelding controleren we referenties van eerdere werkgevers. We verifiëren CV-gegevens en vragen waar nodig om arbeidsreferenties. Alleen medewerkers die deze screening doorstaan, worden toegelaten tot ons netwerk.$$,
  'Kwaliteit & Screening',
  NULL,
  'generated',
  'published',
  'doen-jullie-een-referentiecheck-bij-nieuwe-medewerkers',
  2,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Moet het personeel een VOG (Verklaring Omtrent Gedrag) hebben?',
  $$Voor de meeste functies vragen we inderdaad een VOG. Dit geeft extra zekerheid over de integriteit en betrouwbaarheid van onze medewerkers. Voor bepaalde evenementen of locaties waar dit verplicht is, zorgen wij dat alleen medewerkers met geldige VOG worden ingezet.$$,
  'Kwaliteit & Screening',
  NULL,
  'generated',
  'published',
  'moet-het-personeel-een-vog-verklaring-omtrent-gedrag-hebben',
  3,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hoe gaan jullie om met klachten over medewerkers?',
  $$We nemen elke klacht serieus. Neem direct contact op via +31 6 49 71 37 66 als er iets niet goed gaat. We onderzoeken de situatie, spreken de medewerker aan en komen met een oplossing. Bij structurele problemen wordt de medewerker uit ons netwerk verwijderd.$$,
  'Kwaliteit & Screening',
  NULL,
  'generated',
  'published',
  'hoe-gaan-jullie-om-met-klachten-over-medewerkers',
  4,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Worden medewerkers opgeleid in klantvriendelijkheid?',
  $$Ja, klantvriendelijkheid en hospitaliteit zijn kernwaarden bij TopTalent Jobs. We bieden regelmatig trainingen aan en selecteren bewust op houding en uitstraling. Medewerkers die niet aan onze kwaliteitsstandaard voldoen, krijgen geen vervolgdiensten aangeboden.$$,
  'Kwaliteit & Screening',
  NULL,
  'generated',
  'published',
  'worden-medewerkers-opgeleid-in-klantvriendelijkheid',
  5,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Kan ik feedback geven na een dienst?',
  $$Ja, we moedigen feedback aan! Na elke dienst ontvang je een korte vragenlijst waarin je de medewerker kunt beoordelen. Deze feedback gebruiken we om de kwaliteit te bewaken en te verbeteren. Jouw mening helpt ons om steeds beter te worden.$$,
  'Kwaliteit & Screening',
  NULL,
  'generated',
  'published',
  'kan-ik-feedback-geven-na-een-dienst',
  6,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hebben alle koks een HACCP-certificaat?',
  $$Ja, alle medewerkers die met voedsel werken hebben een geldig HACCP-certificaat. Dit is bij ons verplicht en we controleren dit voor elke dienst. Zo voldoen we aan de wettelijke eisen en waarborg je voedselveiligheid in jouw keuken.$$,
  'Kwaliteit & Screening',
  NULL,
  'generated',
  'published',
  'hebben-alle-koks-een-haccp-certificaat',
  7,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hoe zorgen jullie ervoor dat medewerkers representatief zijn?',
  $$We selecteren medewerkers op uitstraling, verzorging en communicatieve vaardigheden. Voor functies met klantcontact is een nette verschijning en vriendelijke houding essentieel. Bij het intakegesprek beoordelen we of iemand past bij de horeca en bij onze kwaliteitsstandaard.$$,
  'Kwaliteit & Screening',
  NULL,
  'generated',
  'published',
  'hoe-zorgen-jullie-ervoor-dat-medewerkers-representatief-zijn',
  8,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Wat is jullie garantie bij slechte prestaties?',
  $$Als een medewerker niet aan de verwachtingen voldoet, zoeken we direct naar een oplossing. Dit kan betekenen dat we een andere medewerker sturen of een deel van de kosten terugbetalen. Je tevredenheid staat centraal en we lossen dit altijd in goed overleg op.$$,
  'Kwaliteit & Screening',
  NULL,
  'generated',
  'published',
  'wat-is-jullie-garantie-bij-slechte-prestaties',
  9,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Controleren jullie of medewerkers voldoende Nederlands spreken?',
  $$Ja, voor functies met klantcontact eisen we voldoende beheersing van het Nederlands. Tijdens het intakegesprek toetsen we dit. Voor keukenfuncties zonder klantcontact zijn de taaleisen minder streng, maar basisinstructies moeten wel begrepen worden.$$,
  'Kwaliteit & Screening',
  NULL,
  'generated',
  'published',
  'controleren-jullie-of-medewerkers-voldoende-nederlands-spreken',
  10,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Hoe gaan jullie om met no-show van medewerkers?',
  $$No-show is bij ons uiterst zeldzaam door onze strenge screening en betrouwbaarheidscontroles. Mocht het toch gebeuren, dan zoeken we binnen 1-2 uur naar vervanging en zijn de kosten volledig voor onze rekening. We nemen dit zeer serieus.$$,
  'Kwaliteit & Screening',
  NULL,
  'generated',
  'published',
  'hoe-gaan-jullie-om-met-no-show-van-medewerkers',
  11,
  0,
  now(),
  now()
),
(
  gen_random_uuid(),
  'Zijn jullie medewerkers getraind in allergenen en dieetwensen?',
  $$Alle keukenmedewerkers zijn via hun HACCP-opleiding op de hoogte van allergenen. Voor specifieke dieetwensen zoals vegan, halal of glutenvrij adviseren we om dit vooraf te bespreken, zodat we medewerkers kunnen sturen die hier ervaring mee hebben.$$,
  'Kwaliteit & Screening',
  NULL,
  'generated',
  'published',
  'zijn-jullie-medewerkers-getraind-in-allergenen-en-dieetwensen',
  12,
  0,
  now(),
  now()
);
